on: workflow_dispatch
name: Create Branches
jobs:
  build:
    name: Create Branches
    runs-on: ubuntu-latest
    steps:
     - name: Clone
       run: |
          git clone git@github.com:openshift-eng/ocp-build-data.git
          git branch --list | grep openshift-
