on:
  schedule:
    - cron: "*/5 * * * *"

name: Create Branches

jobs:
  build:
    name: Create Branches
    runs-on: ubuntu-latest
    steps:
     - name: Clone
       run: |
          git clone https://github.com/openshift-eng/ocp-build-data/
          git branch --list | grep openshift-
